// camind-page-memory browser bundle — hand-written, no build step.
// Two-level memory bank page: entry list (knowledge / experience tabs) -> entry
// detail. Data comes from the plugin's own Host API (/camind/api/memory).
// Upload is formless by design (docs/memory-design.md §7.3): pick files and
// they are imported immediately; title/description/category/circuit_types/tags
// are generated by the Host-side LLM backfill, cards poll while pending.
// Shared Camind UI modules are declared in dsh.client.external.
//
// Styling: foundation owns semantic tokens and common controls; this bundle's
// scoped pmm-* stylesheet contains domain layout only. The sidebar menu item
// keeps inline fallback styles because it also renders in the official /web UI.
window.__ModuleLoader__.load({ id: "camind-page-memory", factory: (require) => {
var module = { exports: {} }; var exports = module.exports;

const React = require('react')
const { createElement: h, useEffect, useRef, useState } = React
const {
  IconCheckOutline16,
  IconChevronLeftOutline14,
  IconChevronRightOutline14,
  IconEditOutline16,
  IconRefreshOutline14,
  IconThinkOutline16,
  IconTrashOutline16,
  IconWarningOutline16,
} = require('@deepseek-ai/dsh-client-ui-primitives')
const {
  Badge,
  Button,
  Card,
  Chip,
  Dialog,
  Field,
  IconButton,
  Input,
  SidebarAction,
  StateNotice,
  StateView,
  Tabs,
  Tooltip,
} = require('camind-ui-foundation')

const route = '/pages/memory'
const apiBase = '/camind/api/memory'

// --- page stylesheet -----------------------------------------------------------

const pageCss = `
[data-page-memory] { box-sizing: border-box; color: var(--camind-color-text); background: var(--camind-surface-page); font: inherit; }
[data-page-memory] *, [data-page-memory] *::before, [data-page-memory] *::after { box-sizing: border-box; }

.pmm-page1, .pmm-page2 { display: flex; flex-direction: column; height: 100%; overflow: hidden; }
.pmm-head { flex: none; padding: 10px var(--camind-page-inline) 0; }
.pmm-head-row { display: flex; align-items: center; gap: 10px; }
.pmm-title { margin: 0; font-size: 24px; font-weight: 600; line-height: 32px; }
.pmm-lead { flex: 1; min-width: 0; margin: 0; color: var(--camind-color-text-tertiary); font-size: 12px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.pmm-filter { flex: none; display: flex; align-items: center; gap: 8px; flex-wrap: wrap; padding: 12px var(--camind-page-inline); }
.pmm-filter-count { margin-left: auto; color: var(--camind-color-text-tertiary); font-size: 12px; }
.pmm-body { flex: 1; min-height: 0; padding: 4px var(--camind-page-inline) 48px; }
.pmm-search { width: 240px; }

.pmm-control { width: 100%; padding: 7px 10px; border: 1px solid var(--camind-border-default); border-radius: var(--camind-radius-control); background: var(--camind-surface-layer); color: var(--camind-color-text); font: inherit; font-size: 13px; }
.pmm-control:focus-visible { outline: 2px solid var(--camind-focus-ring); outline-offset: 1px; }
.pmm-textarea { min-height: 120px; resize: vertical; line-height: 1.7; }
.pmm-textarea.code { min-height: 340px; font-family: var(--camind-font-mono); font-size: 12px; }

.pmm-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 14px; padding-top: 8px; }
.pmm-entry-card { display: flex; flex-direction: column; height: 100%; padding: 14px 16px; }
.pmm-card-head { display: flex; align-items: center; gap: 8px; }
.pmm-card-title { flex: 1; min-width: 0; font-size: 14px; font-weight: 600; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.pmm-card-chevron { color: var(--camind-color-text-tertiary); }
.pmm-card-name { display: flex; align-items: center; gap: 8px; margin: 4px 0 0; color: var(--camind-color-text-tertiary); font-family: var(--camind-font-mono); font-size: 11px; }
.pmm-card-name .name { flex: 1; min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.pmm-card-name .time { flex: none; }
.pmm-card-desc { margin: 8px 0 0; color: var(--camind-color-text-secondary); font-size: 12px; line-height: 1.6; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; }
.pmm-card-gap { flex: 1; min-height: 12px; }
.pmm-card-badges { display: flex; flex-wrap: nowrap; overflow: hidden; align-items: center; gap: 4px; padding-top: 10px; border-top: 1px solid var(--camind-border-default); }

.pmm-dhead { flex: none; border-bottom: 1px solid var(--camind-border-default); padding: 10px var(--camind-page-inline) 12px; }
.pmm-dhead-row { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; }
.pmm-dhead-name { margin: 0; font-family: var(--camind-font-mono); font-size: 14px; font-weight: 600; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.pmm-dhead-flex { flex: 1; }
.pmm-dbody { flex: 1; min-height: 0; }
.pmm-dbody-inner { padding: 16px var(--camind-page-inline) 64px; }
.pmm-doc-title { margin: 0 0 8px; font-size: 24px; line-height: 32px; font-weight: 600; }
.pmm-doc-desc { margin: 0 0 14px; color: var(--camind-color-text-secondary); font-size: 14px; line-height: 22px; }
.pmm-doc-badges { display: flex; flex-wrap: wrap; align-items: center; gap: 6px; }
.pmm-divider { border: 0; border-top: 1px solid var(--camind-border-default); margin: 20px 0; }
.pmm-pre { margin: 0; padding: 14px 16px; border: 1px solid var(--camind-border-default); border-radius: 10px; background: var(--camind-surface-code); font-family: var(--camind-font-mono); font-size: 12px; line-height: 1.7; overflow-x: auto; white-space: pre-wrap; overflow-wrap: anywhere; }
.pmm-banner { display: flex; align-items: center; gap: 8px; margin-bottom: 16px; padding: 10px 14px; border-radius: 10px; font-size: 13px; }
.pmm-banner.warn { color: var(--camind-color-warning); background: color-mix(in srgb, var(--camind-color-warning) 10%, transparent); }
.pmm-banner.error { color: var(--camind-color-danger); background: color-mix(in srgb, var(--camind-color-danger) 8%, transparent); }
.pmm-sec { margin-bottom: 18px; }
.pmm-sec-title { margin: 0 0 6px; font-size: 12px; font-weight: 600; color: var(--camind-color-text-secondary); letter-spacing: .04em; }
.pmm-sec-body { margin: 0; font-size: 14px; line-height: 1.8; white-space: pre-wrap; overflow-wrap: anywhere; }
.pmm-lesson { border-left: 3px solid var(--camind-color-accent); border-radius: 0 8px 8px 0; padding: 8px 12px; background: color-mix(in srgb, var(--camind-color-accent) 6%, transparent); }
.pmm-evi { display: flex; flex-wrap: wrap; align-items: center; gap: 8px; padding: 8px 0; border-top: 1px solid var(--camind-border-default); font-size: 12px; color: var(--camind-color-text-secondary); }
.pmm-evi:first-of-type { border-top: 0; }
.pmm-mono { font-family: var(--camind-font-mono); font-size: 11px; }

.pmm-dialog-cols { display: grid; grid-template-columns: 280px minmax(0, 1fr); gap: 18px; }
.pmm-danger-action { color: var(--camind-color-danger); }
@media (max-width: 760px) { .pmm-dialog-cols { grid-template-columns: 1fr; } }
`

// --- inline styles (sidebar menu item only, geometry depends on props) -----------

const menuStyles = {
  button(active, wide) {
    return {
      width: wide ? 'calc(100% + 4px)' : 36,
      height: wide ? 42 : 36,
      flex: 'none',
      display: 'flex',
      alignItems: 'center',
      justifyContent: wide ? 'flex-start' : 'center',
      gap: wide ? 8 : 0,
      margin: wide ? '4px -2px' : '4px 0',
      padding: wide ? '0 10px 0 8px' : 0,
      border: 0,
      borderRadius: wide ? 12 : '50%',
      background: active ? 'var(--dsw-alias-interactive-bg-active, var(--dsw-alias-interactive-bg-hover))' : 'transparent',
      color: 'var(--dsw-alias-label-primary)',
      font: 'inherit',
      fontWeight: active ? 600 : 400,
      cursor: 'pointer',
      overflow: 'hidden',
    }
  },
  label: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
}

// --- api -----------------------------------------------------------------------

async function apiSend(method, pathname, payload) {
  const response = await fetch(apiBase + pathname, {
    method,
    headers: payload === undefined ? undefined : { 'content-type': 'application/json' },
    body: payload === undefined ? undefined : JSON.stringify(payload),
  })
  const body = await response.json().catch(() => ({}))
  if (!response.ok) throw new Error(body.error || `请求失败（${response.status}）`)
  return body
}

const apiGet = (pathname) => apiSend('GET', pathname)
const apiPost = (pathname, payload) => apiSend('POST', pathname, payload ?? {})
const apiPut = (pathname, payload) => apiSend('PUT', pathname, payload ?? {})
const apiDelete = (pathname) => apiSend('DELETE', pathname)

function useApi(pathname, deps = []) {
  const [state, setState] = useState({ phase: 'loading', data: null, error: null })
  const [tick, setTick] = useState(0)
  useEffect(() => {
    let alive = true
    setState({ phase: 'loading', data: null, error: null })
    apiGet(pathname).then(
      (data) => { if (alive) setState({ phase: 'ready', data, error: null }) },
      (error) => { if (alive) setState({ phase: 'error', data: null, error: error.message }) },
    )
    return () => { alive = false }
  }, [pathname, tick, ...deps])
  return [state, () => setTick((value) => value + 1)]
}

function relativeTime(iso) {
  const then = new Date(iso).getTime()
  if (!Number.isFinite(then)) return iso ?? ''
  const minutes = Math.floor((Date.now() - then) / 60000)
  if (minutes < 1) return '刚刚'
  if (minutes < 60) return `${minutes} 分钟前`
  const hours = Math.floor(minutes / 60)
  if (hours < 24) return `${hours} 小时前`
  const days = Math.floor(hours / 24)
  if (days < 30) return `${days} 天前`
  return new Date(then).toLocaleDateString()
}

const splitList = (text) => String(text ?? '').split(/[,，;；\n]+/).map((item) => item.trim()).filter(Boolean)

// --- vocabulary ------------------------------------------------------------------

const CATEGORY_LABELS = {
  industry: '行业规范',
  process: '工艺规范',
  circuit: '电路类型',
  enterprise: '企业知识',
  general: '通用',
}
const CATEGORY_TONES = { industry: 'warn', process: 'success', circuit: 'accent', enterprise: 'error', general: null }
const STATUS_LABELS = { draft: '候选', stable: '已采纳', deprecated: '已弃用' }
const STATUS_TONES = { draft: 'warn', stable: 'success', deprecated: null }

// --- level 1: entry list -----------------------------------------------------------

function knowledgeHit(entry, terms) {
  const hay = [entry.name, entry.title, entry.description, ...(entry.tags ?? []), ...(entry.circuit_types ?? [])]
    .join('\n').toLowerCase()
  return terms.every((term) => hay.includes(term))
}

function mergedChips(entry, cap = 4) {
  const seen = new Set()
  const chips = []
  for (const [list, mono] of [[entry.circuit_types ?? [], true], [entry.tags ?? [], false]]) {
    for (const item of list) {
      const key = String(item).toLowerCase()
      if (!key || seen.has(key)) continue
      seen.add(key)
      chips.push({ label: String(item), mono })
    }
  }
  const visible = chips.slice(0, cap)
  return { visible, hidden: chips.length - visible.length }
}

function KnowledgeCard({ entry, navigate }) {
  const pending = entry.metadata_status === 'pending'
  const failed = entry.metadata_status === 'failed'
  const chips = mergedChips(entry)
  return h(Card, {
    className: 'pmm-entry-card',
    dimmed: pending || failed,
    onClick: () => navigate(`${route}/knowledge/${encodeURIComponent(entry.name)}`),
  },
    h('div', { className: 'pmm-card-head' },
      h('span', { className: 'pmm-card-title' }, entry.title),
      pending ? h(Badge, { tone: 'warn' }, '生成中') : null,
      failed ? h(Badge, { tone: 'error' }, '生成失败') : null,
      h('span', { className: 'pmm-card-chevron' }, h(IconChevronRightOutline14, { size: 14 }))),
    h('p', { className: 'pmm-card-name' },
      h('span', { className: 'name' }, entry.name),
      h('span', { className: 'time' }, relativeTime(entry.updated_at))),
    entry.description ? h('p', { className: 'pmm-card-desc' }, entry.description) : null,
    h('div', { className: 'pmm-card-gap' }),
    h('div', { className: 'pmm-card-badges' },
      h(Badge, { tone: CATEGORY_TONES[entry.category] ?? null }, CATEGORY_LABELS[entry.category] ?? entry.category),
      ...chips.visible.map((chip) => h(Badge, { key: chip.label, mono: chip.mono }, chip.label)),
      chips.hidden > 0 ? h(Badge, null, `+${chips.hidden}`) : null))
}

function ExperienceCard({ entry, navigate }) {
  const pending = entry.metadata_status === 'pending'
  const failed = entry.metadata_status === 'failed'
  return h(Card, {
    className: 'pmm-entry-card',
    dimmed: entry.status === 'deprecated' || pending || failed,
    onClick: () => navigate(`${route}/experience/${encodeURIComponent(entry.name)}`),
  },
    h('div', { className: 'pmm-card-head' },
      h(Badge, { tone: STATUS_TONES[entry.status] ?? null }, STATUS_LABELS[entry.status] ?? entry.status),
      h('span', { className: 'pmm-card-title' }, entry.title),
      pending ? h(Badge, { tone: 'warn' }, '生成中') : null,
      failed ? h(Badge, { tone: 'error' }, '生成失败') : null,
      h('span', { className: 'pmm-card-chevron' }, h(IconChevronRightOutline14, { size: 14 }))),
    h('p', { className: 'pmm-card-name' },
      h('span', { className: 'name' }, entry.name),
      h('span', { className: 'time' }, relativeTime(entry.updated_at))),
    entry.trigger ? h('p', { className: 'pmm-card-desc' }, `触发：${entry.trigger}`) : null,
    h('div', { className: 'pmm-card-gap' }),
    h('div', { className: 'pmm-card-badges' },
      entry.confidence != null ? h(Badge, null, `置信度 ${entry.confidence}`) : null,
      h(Badge, null, `证据 ${entry.evidence_count ?? 0}`),
      ...(entry.circuit_types ?? []).slice(0, 2).map((item) => h(Badge, { key: `ct-${item}`, mono: true }, item)),
      (entry.circuit_types ?? []).length > 2 ? h(Badge, null, `+${entry.circuit_types.length - 2}`) : null))
}

function LibraryPage({ navigate, tab }) {
  const [state, refresh] = useApi(`/entries?type=${tab}&status=all&limit=500`)
  const [q, setQ] = useState('')
  const [category, setCategory] = useState('all')
  const [status, setStatus] = useState('all')
  const [uploading, setUploading] = useState(false)
  const fileRef = useRef(null)

  const entries = state.phase === 'ready' ? state.data.entries : []
  const hasPending = entries.some((entry) => entry.metadata_status === 'pending')
  useEffect(() => {
    if (!hasPending) return undefined
    const timer = setInterval(refresh, 3000)
    return () => clearInterval(timer)
  }, [hasPending])

  const onFiles = async (event) => {
    const files = [...(event.target.files ?? [])]
    event.target.value = ''
    if (files.length === 0) return
    setUploading(true)
    try {
      const payload = []
      for (const file of files) payload.push({ filename: file.name, content: await file.text() })
      const result = await apiPost('/entries/knowledge/upload', { files: payload })
      if (result.errors?.length > 0) {
        window.alert(`部分文件未导入：\n${result.errors.map((item) => `${item.filename}：${item.error}`).join('\n')}`)
      }
      refresh()
    } catch (error) {
      window.alert(`上传失败：${error.message}`)
    } finally {
      setUploading(false)
    }
  }

  let body
  if (state.phase === 'loading') {
    body = h(StateView, { kind: 'loading', description: '正在加载记忆库…' })
  } else if (state.phase === 'error') {
    body = h(StateNotice, { onRetry: refresh }, `加载记忆库失败：${state.error}`)
  } else {
    const terms = q.toLowerCase().split(/\s+/).filter(Boolean)
    const filtered = entries.filter((entry) => {
      if (tab === 'knowledge' && category !== 'all' && entry.category !== category) return false
      if (tab === 'experience' && status !== 'all' && entry.status !== status) return false
      return terms.length === 0 || knowledgeHit(entry, terms)
    })
    if (tab === 'experience') {
      const rank = { draft: 0, stable: 1, deprecated: 2 }
      filtered.sort((a, b) => (rank[a.status] ?? 3) - (rank[b.status] ?? 3) || b.updated_at.localeCompare(a.updated_at))
    }
    body = h(React.Fragment, null,
      h('div', { className: 'pmm-filter' },
        h(Input, {
          className: 'pmm-search',
          value: q,
          onChange: (event) => setQ(event.target.value),
          placeholder: '搜索名称 / 描述 / 标签',
        }),
        tab === 'knowledge'
          ? [['all', '全部'], ...Object.entries(CATEGORY_LABELS)].map(([value, label]) =>
            h(Chip, { key: value, selected: category === value, onClick: () => setCategory(value) }, label))
          : [['all', '全部'], ['draft', '候选'], ['stable', '已采纳'], ['deprecated', '已弃用']].map(([value, label]) =>
            h(Chip, {
              key: value,
              selected: status === value,
              onClick: () => setStatus(value),
            }, value === 'all' ? label : `${label} ${entries.filter((entry) => entry.status === value).length}`)),
        h('span', { className: 'pmm-filter-count' }, `${filtered.length} / ${entries.length} 条`)),
      filtered.length === 0
        ? h(StateView, {
          kind: 'empty',
          description: entries.length === 0
            ? (tab === 'knowledge'
              ? '知识库还是空的。点右上角「上传」导入 .md/.txt 文档，元数据会自动生成；或在会话中让 Agent 用 save_memory 保存知识。'
              : '经验库还是空的。Agent 在工作中会用 extract_memory 提炼候选经验，由你在这里审核采纳。')
            : '没有匹配当前过滤条件的条目。',
        })
        : h('div', { className: 'pmm-grid' }, filtered.map((entry) =>
          tab === 'knowledge'
            ? h(KnowledgeCard, { key: entry.name, entry, navigate })
            : h(ExperienceCard, { key: entry.name, entry, navigate }))))
  }

  return h('section', { className: 'pmm-page1', 'data-page-memory': '' },
    h('div', { className: 'pmm-head' },
      h('div', { className: 'pmm-head-row' },
        h('h1', { className: 'pmm-title' }, '记忆库'),
        h('p', { className: 'pmm-lead' },
          tab === 'knowledge'
            ? '人工维护的领域事实与规范，Agent 可通过 search_memory / read_memory 检索。'
            : 'Agent 从工作中提炼的情境化教训；候选经验经人工采纳后生效。'),
        tab === 'knowledge' ? h(React.Fragment, null,
          h('input', {
            ref: fileRef,
            type: 'file',
            accept: '.md,.txt',
            multiple: true,
            style: { display: 'none' },
            onChange: onFiles,
          }),
          h(Button, { variant: 'outline', size: 'sm', disabled: uploading, onClick: () => fileRef.current?.click() },
            uploading ? '上传中…' : '上传')) : null,
        h(IconButton, { label: '刷新', icon: h(IconRefreshOutline14, { size: 14 }), onClick: refresh })),
      h(Tabs, {
        value: tab,
        ariaLabel: '记忆库类型',
        items: [
          { value: 'knowledge', label: '知识库' },
          { value: 'experience', label: '经验库' },
        ],
        onChange: (value) => navigate(value === 'experience' ? `${route}/experience` : route),
      })),
    h('div', { className: 'pmm-body cui-scroll' }, body))
}

// --- level 2: entry detail -----------------------------------------------------------

function KnowledgeEditDialog({ entry, onClose, onSaved }) {
  const fm = entry.frontmatter
  const [title, setTitle] = useState(fm.title ?? '')
  const [description, setDescription] = useState(fm.description ?? '')
  const [category, setCategory] = useState(entry.summary.category ?? 'general')
  const [circuitTypes, setCircuitTypes] = useState((fm.circuit_types ?? []).join(', '))
  const [tags, setTags] = useState((fm.tags ?? []).join(', '))
  const [body, setBody] = useState((entry.body ?? '').replace(/^\n+/, ''))
  const [saving, setSaving] = useState(false)
  const save = async () => {
    setSaving(true)
    try {
      await apiPut(`/entries/knowledge/${encodeURIComponent(entry.name)}`, {
        title, description, category,
        circuit_types: splitList(circuitTypes),
        tags: splitList(tags),
        body,
      })
      onSaved()
    } catch (error) {
      window.alert(`保存失败：${error.message}`)
      setSaving(false)
    }
  }
  return h(Dialog, {
    size: 'wide',
    title: `编辑知识条目 ${entry.name}`,
    onClose,
    footer: h(React.Fragment, null,
      h(Button, { variant: 'ghost', onClick: onClose }, '取消'),
      h(Button, { variant: 'primary', disabled: saving, onClick: save }, saving ? '保存中…' : '保存')),
  },
    h('div', { className: 'pmm-dialog-cols' },
      h('div', null,
        h(Field, { label: '标题' }, h(Input, { value: title, onChange: (event) => setTitle(event.target.value) })),
        h(Field, { label: '描述', hint: '检索召回的关键；与标题一起留空则保存后自动生成' },
          h('textarea', { className: 'pmm-control pmm-textarea', style: { minHeight: 64 }, value: description, onChange: (event) => setDescription(event.target.value) })),
        h(Field, { label: '分类' },
          h('select', { className: 'pmm-control', value: category, onChange: (event) => setCategory(event.target.value) },
            Object.entries(CATEGORY_LABELS).map(([value, label]) => h('option', { key: value, value }, label)))),
        h(Field, { label: '电路类型', hint: '逗号分隔，如 bgr, ldo' },
          h(Input, { value: circuitTypes, onChange: (event) => setCircuitTypes(event.target.value) })),
        h(Field, { label: '标签', hint: '逗号分隔' },
          h(Input, { value: tags, onChange: (event) => setTags(event.target.value) }))),
      h(Field, { label: '正文（markdown）' },
        h('textarea', { className: 'pmm-control pmm-textarea code', value: body, onChange: (event) => setBody(event.target.value) }))))
}

function ExperienceEditDialog({ entry, onClose, onSaved }) {
  const fm = entry.frontmatter
  const sections = entry.sections ?? { situation: '', lesson: '', action: '' }
  const [title, setTitle] = useState(fm.title ?? '')
  const [trigger, setTrigger] = useState(fm.trigger ?? '')
  const [situation, setSituation] = useState(sections.situation)
  const [lesson, setLesson] = useState(sections.lesson)
  const [action, setAction] = useState(sections.action)
  const [saving, setSaving] = useState(false)
  const save = async () => {
    setSaving(true)
    try {
      await apiPut(`/entries/experience/${encodeURIComponent(entry.name)}`, { title, trigger, situation, lesson, action })
      onSaved()
    } catch (error) {
      window.alert(`保存失败：${error.message}`)
      setSaving(false)
    }
  }
  return h(Dialog, {
    title: `编辑经验 ${entry.name}`,
    onClose,
    footer: h(React.Fragment, null,
      h(Button, { variant: 'ghost', onClick: onClose }, '取消'),
      h(Button, { variant: 'primary', disabled: saving, onClick: save }, saving ? '保存中…' : '保存')),
  },
    h(Field, { label: '标题' }, h(Input, { value: title, onChange: (event) => setTitle(event.target.value) })),
    h(Field, { label: '触发条件' }, h(Input, { value: trigger, onChange: (event) => setTrigger(event.target.value) })),
    h(Field, { label: '情境' }, h('textarea', { className: 'pmm-control pmm-textarea', value: situation, onChange: (event) => setSituation(event.target.value) })),
    h(Field, { label: '教训' }, h('textarea', { className: 'pmm-control pmm-textarea', value: lesson, onChange: (event) => setLesson(event.target.value) })),
    h(Field, { label: '做法' }, h('textarea', { className: 'pmm-control pmm-textarea', value: action, onChange: (event) => setAction(event.target.value) })))
}

function DetailPage({ navigate, type, name }) {
  const [state, refresh] = useApi(`/entries/${type}/${encodeURIComponent(name)}`)
  const [editing, setEditing] = useState(false)
  const [acting, setActing] = useState(false)

  const entry = state.phase === 'ready' ? state.data : null
  const pending = entry?.frontmatter?.metadata_status === 'pending'
  useEffect(() => {
    if (!pending) return undefined
    const timer = setInterval(refresh, 3000)
    return () => clearInterval(timer)
  }, [pending])

  if (state.phase === 'loading') {
    return h('section', { className: 'pmm-page2', 'data-page-memory': '' },
      h('div', { style: { padding: '16px var(--camind-page-inline)' } },
        h(StateView, { kind: 'loading', description: '正在加载记忆条目…' })))
  }
  if (state.phase === 'error') {
    return h('section', { className: 'pmm-page2', 'data-page-memory': '' },
      h('div', { style: { padding: '16px clamp(16px, 3vw, 32px)' } },
        h(StateNotice, { onRetry: refresh }, `加载条目失败：${state.error}`)))
  }

  const fm = entry.frontmatter
  const summary = entry.summary
  const listPath = type === 'experience' ? `${route}/experience` : route

  const run = async (fn) => {
    setActing(true)
    try { await fn() } catch (error) { window.alert(error.message) } finally { setActing(false) }
  }
  const doDelete = () => run(async () => {
    if (!window.confirm(`删除条目 ${name}？\n删除会作为一次 git commit 落盘，可从历史恢复。`)) return
    await apiDelete(`/entries/${type}/${encodeURIComponent(name)}`)
    navigate(listPath)
  })
  const doPromote = () => run(async () => { await apiPost(`/entries/experience/${encodeURIComponent(name)}/promote`); refresh() })
  const doDeprecate = () => run(async () => { await apiPost(`/entries/experience/${encodeURIComponent(name)}/deprecate`); refresh() })

  const metadataBadge = summary.metadata_status && summary.metadata_status !== 'ready'
    ? h(Badge, { tone: summary.metadata_status === 'pending' ? 'warn' : 'error' },
      summary.metadata_status === 'pending' ? '元数据生成中' : '元数据生成失败')
    : null

  return h('section', { className: 'pmm-page2', 'data-page-memory': '' },
    h('div', { className: 'pmm-dhead' },
      h('div', { className: 'pmm-dhead-row' },
        h(IconButton, { label: '返回列表', icon: h(IconChevronLeftOutline14, { size: 14 }), onClick: () => navigate(listPath) }),
        h('h1', { className: 'pmm-dhead-name' }, name),
        type === 'knowledge'
          ? h(Badge, { tone: CATEGORY_TONES[summary.category] ?? null }, CATEGORY_LABELS[summary.category] ?? summary.category)
          : h(Badge, { tone: STATUS_TONES[summary.status] ?? null }, STATUS_LABELS[summary.status] ?? summary.status),
        metadataBadge,
        h('span', { className: 'pmm-dhead-flex' }),
        type === 'experience' && summary.status !== 'stable'
          ? h(Button, { variant: 'outline', size: 'sm', icon: h(IconCheckOutline16, { size: 14 }), disabled: acting, onClick: doPromote }, '采纳')
          : null,
        type === 'experience' && summary.status !== 'deprecated'
          ? h(Button, { variant: 'outline', size: 'sm', disabled: acting, onClick: doDeprecate }, '弃用')
          : null,
        h(Button, { variant: 'outline', size: 'sm', icon: h(IconEditOutline16, { size: 14 }), onClick: () => setEditing(true) }, '编辑'),
        h(Button, { variant: 'outline', size: 'sm', className: 'pmm-danger-action', icon: h(IconTrashOutline16, { size: 14 }), disabled: acting, onClick: doDelete }, '删除'))),
    h('div', { className: 'pmm-dbody cui-scroll' },
      h('div', { className: 'pmm-dbody-inner' },
        pending
          ? h('div', { className: 'pmm-banner warn' }, type === 'knowledge'
            ? '元数据（标题 / 描述 / 分类 / 标签）正在由 AI 自动生成，数秒后自动刷新。'
            : '元数据（标题 / 描述 / 标签）正在由 AI 自动生成，数秒后自动刷新。')
          : null,
        summary.metadata_status === 'failed'
          ? h('div', { className: 'pmm-banner error' }, h(IconWarningOutline16, { size: 14 }), '元数据自动生成失败。可点「编辑」手动填写，保存即生效。')
          : null,
        h('h2', { className: 'pmm-doc-title' }, fm.title ?? name),
        fm.description ? h('p', { className: 'pmm-doc-desc' }, fm.description) : null,
        h('div', { className: 'pmm-doc-badges' },
          ...(summary.circuit_types ?? []).map((item) => h(Badge, { key: `ct-${item}`, mono: true }, item)),
          ...(summary.tags ?? []).map((item) => h(Badge, { key: `tag-${item}` }, item)),
          type === 'experience' && summary.confidence != null ? h(Badge, null, `置信度 ${summary.confidence}`) : null,
          type === 'experience' ? h(Badge, null, `证据 ${summary.evidence_count ?? 0}`) : null,
          h(Badge, null, `更新于 ${relativeTime(summary.updated_at)}`)),
        h('hr', { className: 'pmm-divider' }),
        type === 'experience'
          ? h(React.Fragment, null,
            h('div', { className: 'pmm-sec' },
              h('p', { className: 'pmm-sec-title' }, '触发条件'),
              h('p', { className: 'pmm-sec-body' }, fm.trigger ?? '—')),
            h('div', { className: 'pmm-sec' },
              h('p', { className: 'pmm-sec-title' }, '情境'),
              h('p', { className: 'pmm-sec-body' }, entry.sections?.situation || '—')),
            h('div', { className: 'pmm-sec' },
              h('p', { className: 'pmm-sec-title' }, '教训'),
              h('div', { className: 'pmm-lesson' },
                h('p', { className: 'pmm-sec-body' }, entry.sections?.lesson || '—'))),
            h('div', { className: 'pmm-sec' },
              h('p', { className: 'pmm-sec-title' }, '做法'),
              h('p', { className: 'pmm-sec-body' }, entry.sections?.action || '—')),
            fm.signature && typeof fm.signature === 'object' && Object.keys(fm.signature).length > 0
              ? h('div', { className: 'pmm-sec' },
                h('p', { className: 'pmm-sec-title' }, '特征签名'),
                h('div', { className: 'pmm-doc-badges' },
                  Object.entries(fm.signature).map(([key, value]) =>
                    h(Badge, { key, mono: true }, `${key}: ${value}`))))
              : null,
            Array.isArray(fm.refs) && fm.refs.length > 0
              ? h('div', { className: 'pmm-sec' },
                h('p', { className: 'pmm-sec-title' }, '范本原件'),
                fm.refs.map((ref, index) => h('p', { className: 'pmm-mono', key: index }, ref)))
              : null,
            Array.isArray(fm.evidence) && fm.evidence.length > 0
              ? h('div', { className: 'pmm-sec' },
                h('p', { className: 'pmm-sec-title' }, '证据链'),
                fm.evidence.map((item, index) =>
                  h('div', { className: 'pmm-evi', key: index },
                    h(Badge, null, item.source ?? 'unknown'),
                    h('span', { className: 'pmm-mono' }, item.ref ?? ''),
                    item.outcome ? h(Badge, { tone: item.outcome === 'pass' ? 'success' : 'warn' }, item.outcome) : null,
                    h('span', null, item.at ?? ''))))
              : null)
          : h('pre', { className: 'pmm-pre' }, (entry.body ?? '').replace(/^\n+/, '')))),
    editing
      ? (type === 'knowledge'
        ? h(KnowledgeEditDialog, { entry, onClose: () => setEditing(false), onSaved: () => { setEditing(false); refresh() } })
        : h(ExperienceEditDialog, { entry, onClose: () => setEditing(false), onSaved: () => { setEditing(false); refresh() } }))
      : null)
}

// --- page routing --------------------------------------------------------------------

function isPagePath(pathname) {
  return pathname === route || pathname.startsWith(route + '/')
}

function MemoryPage({ matched }) {
  const { pathname, navigate } = matched
  const rest = pathname.slice(route.length)
  const segments = rest.split('/').filter(Boolean).map(decodeURIComponent)
  let page
  if (segments.length >= 2 && (segments[0] === 'knowledge' || segments[0] === 'experience')) {
    page = h(DetailPage, { key: `${segments[0]}/${segments[1]}`, navigate, type: segments[0], name: segments[1] })
  } else {
    const tab = segments[0] === 'experience' ? 'experience' : 'knowledge'
    page = h(LibraryPage, { key: tab, navigate, tab })
  }
  return page
}

// --- sidebar entry ---------------------------------------------------------------------

function MemoryMenuItem({ wide, pathname, navigate }) {
  // The official shell (served at /web) renders this list with { wide } only —
  // the route-aware props are a /camind extension, so degrade gracefully there.
  const active = typeof pathname === 'string' && isPagePath(pathname)
  const open = () => {
    if (typeof navigate === 'function') navigate(route)
    else location.assign('/camind' + route)
  }
  if (typeof navigate === 'function') {
    return h(SidebarAction, {
      wide,
      active,
      icon: h(IconThinkOutline16, { size: wide ? 16 : 18 }),
      label: '记忆库',
      onClick: open,
    })
  }
  const button = h('button', {
    type: 'button',
    'aria-label': '打开记忆库页面',
    'aria-current': active ? 'page' : undefined,
    style: menuStyles.button(active, wide),
    onClick: open,
    onPointerEnter: (event) => {
      if (!active) event.currentTarget.style.background = 'var(--dsw-alias-interactive-bg-hover)'
    },
    onPointerLeave: (event) => {
      if (!active) event.currentTarget.style.background = 'transparent'
    },
  },
  h(IconThinkOutline16, { size: wide ? 16 : 18 }),
  wide ? h('span', { style: menuStyles.label }, '记忆库') : null)

  return h(Tooltip, { label: '记忆库', delayMs: 500, disabled: wide }, button)
}

function apply(ctx) {
  if (location.pathname === '/camind' || location.pathname.startsWith('/camind/')) {
    ctx.effect(() => {
      const style = document.createElement('style')
      style.setAttribute('data-camind-page-memory', '')
      style.textContent = pageCss
      document.head.appendChild(style)
      return () => { style.remove() }
    }, 'page-memory: stylesheet')
  }

  ctx.slots.inject('sidebar.footer.action', () =>
    ctx.slots.register({
      name: 'sidebar.footer.action',
      id: 'page-memory',
      order: 20,
      label: '记忆库',
    }, MemoryMenuItem))

  ctx.slots.inject('shell.content', () =>
    ctx.slots.register({
      name: 'shell.content',
      priority: 100,
      select: ({ pathname, navigate }) => {
        if (!isPagePath(pathname)) return null
        return { pathname, navigate }
      },
    }, MemoryPage))
}

exports.name = 'page-memory-client'
exports.inject = ['slots']
exports.apply = apply

return module.exports; } });
